version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    resource_class: large
    environment:
      GOPROXY: https://proxy.golang.org
      GO111MODULE: "on"
      SASS_VERSION: 1.63.2
      DART_SASS_SHA_LINUX: 3ea33c95ad5c35fda6e9a0956199eef38a398f496cfb8750e02479d7d1dd42af
      HUGO_BUILD_TAGS: extended
    steps:
      - run:
          name: Runner Info
          command: |
            lscpu
            free -h
            df -h
      - checkout
      - run:
          name: Install Go
          command: |
            wget -q https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin' >> "$BASH_ENV"
      - run:
          name: Install dependencies
          command: |
            go install github.com/magefile/mage@v1.15.0
            sudo apt-get update -y && sudo apt-get install -y pandoc
            pip install docutils
            sudo gem install asciidoctor
            curl -LJO "https://github.com/sass/dart-sass/releases/download/${SASS_VERSION}/dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
            echo "${DART_SASS_SHA_LINUX}  dart-sass-${SASS_VERSION}-linux-x64.tar.gz" | sha256sum -c
            tar -xvf "dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
            echo 'export PATH=$PATH:'"$(pwd)"'/dart-sass/' >> "$BASH_ENV"
      - run:
          name: Test
          command: |
            sass --version
            mage -v check

workflows:
  benchmark:
    jobs:
      - test
