name: Test
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'

env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on
  SASS_VERSION: 1.63.2
  DART_SASS_SHA_LINUX: 3ea33c95ad5c35fda6e9a0956199eef38a398f496cfb8750e02479d7d1dd42af

permissions:
  contents: read

jobs:
  test:
    name: GitHub / 4cpu
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "::group::CPU"
          lscpu
          echo "::endgroup::"
          echo "::group::Memory"
          free -h
          echo "::endgroup::"
          echo "::group::Disk"
          df -h
          echo "::endgroup::"
      - name: Checkout start
        run: echo "CHECKOUT_START=$(date +%s)" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout end
        run: echo "Checkout took $(( $(date +%s) - CHECKOUT_START )) seconds"
      - name: Install start
        run: echo "INSTALL_START=$(date +%s)" >> "$GITHUB_ENV"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true
          cache: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tools
        run: |
          go install github.com/magefile/mage@v1.15.0
          sudo apt-get update -y && sudo apt-get install -y pandoc
          pip install docutils
          curl -LJO "https://github.com/sass/dart-sass/releases/download/${SASS_VERSION}/dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
          echo "${DART_SASS_SHA_LINUX}  dart-sass-${SASS_VERSION}-linux-x64.tar.gz" | sha256sum -c
          tar -xvf "dart-sass-${SASS_VERSION}-linux-x64.tar.gz"
          echo "$GITHUB_WORKSPACE/dart-sass/" >> $GITHUB_PATH
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: false
      - uses: reitzig/actions-asciidoctor@v2
      - name: Install end
        run: echo "Install took $(( $(date +%s) - INSTALL_START )) seconds"
      - name: Test start
        run: echo "TEST_START=$(date +%s)" >> "$GITHUB_ENV"
      - name: Test
        run: |
          sass --version
          mage -v check
        env:
          HUGO_BUILD_TAGS: extended
      - name: Test end
        run: echo "Test took $(( $(date +%s) - TEST_START )) seconds"
